In [2]:
import numpy as np

# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print(f"Random 10x10 Matrix A: {random_matrix_A}")

# Generate another random 10x10 matrix
random_matrix_B = np.random.rand(10, 10)
print(f"Random 10x1 Matrix B: {random_matrix_B}")

# Matrix Addition
addition_result = random_matrix_A + random_matrix_B
print(f"Matrix Addition Result: {addition_result}")

# Matrix Subtraction
subtraction_result = random_matrix_A - random_matrix_B
print(f"Matrix Subtraction Result: {subtraction_result}")

# Matrix Multiplication
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print(f"Matrix Multiplication Result: {multiplication_result}")

# Transpose of random_matrix_A
transpose_result_A = np.transpose(random_matrix_A)
print(f"Transpose of Matrix A: {transpose_result_A}")

# Transpose of random_matrix_B
transpose_result_B = np.transpose(random_matrix_B)
print(f"Transpose of Matrix B: {transpose_result_B}")

Random 10x10 Matrix A: [[0.91696202 0.12088327 0.21159938 0.13322327 0.20030322 0.09761431
  0.25763112 0.72179508 0.14554312 0.15543744]
 [0.73113126 0.81454644 0.2885939  0.34668165 0.57623397 0.06471175
  0.44752515 0.4205892  0.1047678  0.21644515]
 [0.78802964 0.84988206 0.50998138 0.61146997 0.99195858 0.9258687
  0.21133684 0.32544663 0.30178124 0.61686236]
 [0.71427802 0.12729841 0.94573807 0.38781009 0.84446024 0.82380715
  0.95299536 0.33412275 0.69283693 0.04067323]
 [0.71406841 0.25661753 0.73714446 0.77558143 0.06762248 0.41613803
  0.37374156 0.80092245 0.9006336  0.25301626]
 [0.44293756 0.5293976  0.63754145 0.22137726 0.00234694 0.89634281
  0.93357094 0.80280958 0.66473981 0.6062513 ]
 [0.23505434 0.46566169 0.4286276  0.73616959 0.23123867 0.87578739
  0.02369697 0.30028941 0.12349222 0.25437792]
 [0.23460859 0.25392168 0.33165902 0.64022275 0.39307418 0.34140182
  0.8147901  0.09992202 0.57874518 0.78453772]
 [0.62104712 0.92849272 0.5871361  0.06776425 0.04295897 0

In [3]:
"""""
1. Matrix Creation & Structure
Question: Explain what a matrix is and provide an example of 3x2 matrix.
          Using NumPy, write code to create this matrix.
"""""

"""""
A matrix is a 2D array of numbers arranged in rows and columns.
"""""
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8], [9, 10]])

# Matrix Multiplication
multiplication_result = np.dot(A, B)
print(f"A * B: {multiplication_result}")

A * B: [[ 25  28]
 [ 57  64]
 [ 89 100]]


In [5]:
"""""
2. Basic Matrix Operations
Question: Given two matrices A and B, describe the conditions necessary for
          performing matrix addition and multiplication. Write the code to add
          multiply two 5x5 matrices using NumPy
"""""

random_matrix_A = np.random.rand(5, 5)
random_matrix_B = np.random.rand(5, 5)

multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print(f"A * B: {multiplication_result}")

A * B: [[0.63211204 1.18273888 1.00686624 1.11511735 0.48308019]
 [0.92252332 1.78522398 1.50561692 1.74887405 1.04290076]
 [0.61152413 1.39044959 1.51579292 1.43212863 1.4516384 ]
 [1.03914021 1.68873958 1.7215947  1.35143593 1.30347579]
 [0.8443194  1.51250743 1.51803313 1.16698455 1.36860412]]


In [7]:
"""""
3. Transpose of a Matrix
Question: Explain the concept of matrix transposition. What effect does it have
          on a 3x2 matrix? Write the code to create a 3x2 matrix and find its
          transpose.
"""""

"""""
The transpose of a matrix is a flipped version of the original matrix,
where the rows and columns are switched
"""""
C = np.array([[1, 2], [4, 5], [6, 7]])
D = np.array([[8, 9], [10, 11]])

transpose_result_C = np.transpose(C)
print(f"Transpose of Matrix C: {transpose_result_C}")

transpose_result_D = np.transpose(D)
print(f"Transpose of Matrix D: {transpose_result_D}")

Transpose of Matrix C: [[1 4 6]
 [2 5 7]]
Transpose of Matrix D: [[ 8 10]
 [ 9 11]]


In [8]:
"""""
4. Working with Large Matrices
Question: Create a random 5x5 matrix using NumPy. Compute the sum of all
          elements in the matrix, then find its transpose. Print both the sum
          and the transpose of the matrix
"""""

random_matrix_A = np.random.rand(5, 5)
print(f"Random 5x5 Matrix A: {random_matrix_A}")

sum_of_elements = np.sum(random_matrix_A)
print(f"Sum of Elements in Matrix A: {sum_of_elements}")

transpose_result_A = np.transpose(random_matrix_A)
print(f"Transpose of Matrix A: {transpose_result_A}")

Random 5x5 Matrix A: [[0.18998705 0.50138472 0.55776335 0.54198689 0.84443219]
 [0.8598619  0.69435295 0.42713308 0.39329953 0.04691227]
 [0.40190718 0.36423251 0.50146112 0.36353777 0.38458115]
 [0.65315736 0.64362133 0.18930171 0.02214367 0.9062396 ]
 [0.41408068 0.6195422  0.52244133 0.78006596 0.8281368 ]]
Sum of Elements in Matrix A: 12.65156430240026
Transpose of Matrix A: [[0.18998705 0.8598619  0.40190718 0.65315736 0.41408068]
 [0.50138472 0.69435295 0.36423251 0.64362133 0.6195422 ]
 [0.55776335 0.42713308 0.50146112 0.18930171 0.52244133]
 [0.54198689 0.39329953 0.36353777 0.02214367 0.78006596]
 [0.84443219 0.04691227 0.38458115 0.9062396  0.8281368 ]]


In [9]:
"""""
5. Applying Matrix Operations in Context
Question: Suppose you have two random 10x10 matrice D & E. Write code to:
          (A) Add the matrices
          (B) Subtract E from D
          (C) Multiply D and E
          Print each result and describe one possible applicaiton of each
          operation in computer science.
"""""

"""""
Addition: Representing and manipulating images.
Subtraction: Calculating differences between images or data sets
Multiplication: Transforming graphical objects in computer graphics and
                gaming or representing relationships in graph theory.
"""""

random_matrix_D = np.random.rand(10, 10)
random_matrix_E = np.random.rand(10, 10)

addition_result = random_matrix_D + random_matrix_E
print(f"D + E: {addition_result}")

subtraction_result = random_matrix_E - random_matrix_D
print(f"E - D: {subtraction_result}")

multiplication_result = np.dot(random_matrix_D, random_matrix_E)
print(f"D * E: {multiplication_result}")

D + E: [[1.52024523 1.02777258 0.55770593 0.200595   1.30822155 0.37024512
  1.31678515 0.99942966 1.08234569 0.70330403]
 [0.55900208 1.37033892 0.16299259 1.42950774 1.60623083 1.14266176
  0.94076679 1.58413221 1.05354026 0.99050173]
 [1.00934429 1.03446028 0.85987781 1.15587682 1.81820824 1.39230364
  1.3979856  0.93757506 0.6051039  0.9544266 ]
 [0.72450896 1.32925976 0.92451042 0.41552647 0.69979748 0.97932965
  1.81339833 0.87499447 0.970982   1.43221555]
 [1.04344994 0.7471057  1.20846752 0.87012561 1.30810073 0.47033122
  0.97094704 0.50887995 0.5536373  1.07318175]
 [1.1949694  1.17536641 0.74910414 1.31943876 1.48375461 1.36215507
  1.20719681 1.63727293 1.02744542 1.14564699]
 [0.92830889 0.14980792 0.51475746 1.25482703 0.81519023 0.46741747
  0.25854095 0.67455745 1.37635511 0.84316354]
 [0.97105494 1.78910943 0.96458868 1.27833652 0.34129008 1.49291907
  1.16769145 1.05635276 1.20662626 1.86705803]
 [1.64479407 0.6238941  1.06350765 0.59181265 0.85735601 0.94392599
  1.2