**Section 1: Transpose of a Matrix and Symmetric Matrices**

**Practice Problem 1**

In [3]:
"""""
Q1: What are some examples of unary operations in matries?
- Transpose: Flipping the matrix over its diagonal.
- Trace: The sum of the diagonal elements.
- Determinant: A scalar value that represents certain properties of the Matrix.
"""""

'""\nQ1: What are some examples of unary operations in matries?\n- Transpose: Flipping the matrix over its diagonal.\n- Trace: The sum of the diagonal elements.\n- Determinant: A scalar value that represents certain properties of the Matrix.\n'

In [4]:
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
"""""
Q2: Check if matrix_A is a symmetri matrix. Modify the code below to verify this.
"""""
is_symmetric = (matrix_A == transpose_A).all()
print("\nIs this matrix a symmetric?", is_symmetric)


Is this matrix a symmetric? False


In [6]:
# Pre-generated matrix test
matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8,],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])

transpose_matrix_B = matrix_B.T

print("Matrix B:\n", matrix_B)
print("\nTranspose of Matrix B:\n", transpose_matrix_B)

is_symmetric = (matrix_B == transpose_matrix_B).all()
print("\nIs this matrix a symmetric?", is_symmetric)

Matrix B:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of Matrix B:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Is this matrix a symmetric? False


In [7]:
# Random matrix test
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

symmetric_matrix = (random_matrix + random_matrix.T) // 2

print("Random Matrix:\n", random_matrix)
print("\nTranspose of Random Matrix:\n", transpose_random)

is_symmetric = (symmetric_matrix == symmetric_matrix.T).all()
print("\nIs this matrix a symmetric?", is_symmetric)

Random Matrix:
 [[6 4 3 5]
 [4 5 9 7]
 [4 4 8 8]
 [5 7 1 3]]

Transpose of Random Matrix:
 [[6 4 4 5]
 [4 5 4 7]
 [3 9 8 1]
 [5 7 8 3]]

Is this matrix a symmetric? True


**Section 2: Trace of a Matrix**

In [8]:
# Calculate the trace of matrix_A
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)


Trace of Matrix A: 15


In [9]:
"""""
Q3: What is the trace of following matrix?
"""""

matrix_C = np.array([[10, 20, 30],
                     [5, 15, 25],
                     [2, 4, 6]])

trace_C = np.trace(matrix_C)
print("\nTrace of Matrix C:", trace_C)


Trace of Matrix C: 31


**Practice Problem 2**

In [10]:
# Pre-generated 5x5 matrix
pre_matrix_A = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]])

trace_pre_matrix_A = np.trace(pre_matrix_A)
print("\nTrace of Matrix A:", trace_pre_matrix_A)


Trace of Matrix A: 65


**Section 3: Determinant using the Cofactor Method**

In [11]:
# Determinant using NumPy
det_A = np.linalg.det(matrix_A)
print("\nDeterminant of Matrix A:", det_A)


Determinant of Matrix A: 0.0


In [12]:
matrix_d = np.array([[4, 6],
                     [3, 8]])

det_D = (matrix_d[0,0] * matrix_d[1,1]) - (matrix_d[0,1] * matrix_d[1,0])
print("\nDeterminant of Matrix C:", det_D)


Determinant of Matrix C: 14


**Practice Problem 3**


In [13]:
# Compute the determinant of the folowing 3x3 matrix using NumPy:

matrix_E = np.array([[1, 2, 3],
                   [0, 4, 5],
                   [1, 0, 6]])

det_E = np.linalg.det(matrix_E)

print("Matrix E:\n", matrix_E)
print("\nDeterminant of Matrix E:", det_E)

Matrix E:
 [[1 2 3]
 [0 4 5]
 [1 0 6]]

Determinant of Matrix E: 22.000000000000004


**Practice Problem #4**

In [15]:
random_matrix_A = np.random.randint(1, 10, (3, 33))

transpose_random = random_matrix_A.T

print("Random Matrix A:\n", random_matrix_A)
print("\nTranspose of Random Matrix A:\n", transpose_random)

Random Matrix A:
 [[8 2 7 9 7 5 4 5 7 7 2 2 2 7 6 5 8 8 6 4 5 1 9 4 3 6 8 3 2 4 4 8 1]
 [6 2 3 4 5 8 3 3 9 3 1 2 6 7 6 1 5 7 9 9 5 6 6 4 1 5 4 2 3 5 1 4 2]
 [1 5 6 7 3 9 7 1 1 9 9 9 9 7 2 2 4 4 4 1 6 5 6 7 4 9 2 9 7 1 3 2 3]]

Transpose of Random Matrix A:
 [[8 6 1]
 [2 2 5]
 [7 3 6]
 [9 4 7]
 [7 5 3]
 [5 8 9]
 [4 3 7]
 [5 3 1]
 [7 9 1]
 [7 3 9]
 [2 1 9]
 [2 2 9]
 [2 6 9]
 [7 7 7]
 [6 6 2]
 [5 1 2]
 [8 5 4]
 [8 7 4]
 [6 9 4]
 [4 9 1]
 [5 5 6]
 [1 6 5]
 [9 6 6]
 [4 4 7]
 [3 1 4]
 [6 5 9]
 [8 4 2]
 [3 2 9]
 [2 3 7]
 [4 5 1]
 [4 1 3]
 [8 4 2]
 [1 2 3]]


**Practice Problem #5**

In [16]:
random_matrix = np.random.randint(1, 10, (3, 3))

symmetric_matrix = (random_matrix + random_matrix.T) / 2

is_symmetric = np.allclose(symmetric_matrix, symmetric_matrix.T)

# Print results
print("Random Matrix:\n", random_matrix)
print("\nSymmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric?:", is_symmetric)

Random Matrix:
 [[2 2 1]
 [7 9 8]
 [2 8 6]]

Symmetric Matrix:
 [[2.  4.5 1.5]
 [4.5 9.  8. ]
 [1.5 8.  6. ]]

Is the matrix symmetric?: True
