**Practice Problem #1**

In [1]:
import numpy as np

# Define the matrix A
A = np.array([[3, 4],
              [2, 5]])

# Calculate the determinant
det_A = np.linalg.det(A)

# Check if the determinant is non-zero
if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Matrix A:\n", A)
    print("\nDeterminant of A:", det_A)
    print("\nInverse of A:\n", A_inv)
else:
    print("Matrix A is singular and does not have an inverse.")

Matrix A:
 [[3 4]
 [2 5]]

Determinant of A: 7.000000000000001

Inverse of A:
 [[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


**Practice Problem #2**

In [3]:
# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, 3],
              [4, -1]])
B = np.array([7, 5])

# Solve for X (x and y)
try:
    X = np.linalg.solve(A, B)
    print("Solution to the system of equations:")
    print("x =", X[0])
    print("y =", X[1])
except np.linalg.LinAlgError:
    print("The system of equations does not have a unique solution.")

Solution to the system of equations:
x = 1.5714285714285714
y = 1.2857142857142858


**Practice Problem #3**

In [4]:
# Define the matrix A
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Calculate the determinant
det_A = np.linalg.det(A)

# Check if the determinant is non-zero
if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Matrix A:\n", A)
    print("\nDeterminant of A:", det_A)
    print("\nInverse of A:\n", A_inv)
else:
    print("Matrix A is singular and does not have an inverse.")

Matrix A:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of A: 0.9999999999999964

Inverse of A:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


**Practice Problem #4**

In [5]:
# Define the coefficient matrix A and the constant matrix B
A = np.array([[1, 1, 1],
              [2, 5, 1],
              [2, 3, 8]])
B = np.array([6, -4, 9])

# Solve using the matrix inverse
try:
    # Calculate the inverse of A
    A_inv = np.linalg.inv(A)
    # Solve for X
    X = np.dot(A_inv, B)
    print("Solution to the system of equations:")
    print("x =", X[0])
    print("y =", X[1])
    print("z =", X[2])
except np.linalg.LinAlgError:
    print("The coefficient matrix A is singular; the system cannot be solved with the matrix inverse method.")

Solution to the system of equations:
x = 10.842105263157896
y = -5.210526315789474
z = 0.3684210526315789


**Practice Problem #5**

In [6]:
# Define matrix A and vector b
A = np.array([[4, -1, 0],
              [3, 5, 2],
              [-2, 4, 1]])
b = np.array([5, 6, 2])

# Solve for x
try:
    x = np.linalg.solve(A, b)  # Direct method to solve Ax = b
    print("Solution vector x:")
    print(x)
except np.linalg.LinAlgError:
    print("Matrix A is singular; the system cannot be solved.")

Solution vector x:
[  2.6   5.4 -14.4]
