**Matrix Generation**

In [ ]:
import numpy as np

# Step 1: Generate a 3 x 4 random matrix
matrix_3x4 = np.random.randint(1, 21, size = (3, 4)) # Adjust range as needed

A = matrix_3x4[:, :3] # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3] # Right-hand side vector (last column)

print("Generated 3 x 4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-Hand Side Vector (b):")
print(b)

Generated 3 x 4 Matrix:
[[19 12  1 16]
 [13 13 18 18]
 [11 10  5 14]]

Coefficient Matrix (A):
[[19 12  1]
 [13 13 18]
 [11 10  5]]

Right-Hand Side Vector (b):
[16 18 14]


**Solution Verifier**

In [ ]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A) # Compute A^-1
    x_manual = np.dot(A_inv, b) # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted!")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)
print("\nSolution using Gaussian Elimination (NumpPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian) # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Solution using Matrix Inverse Method:
[-0.16943522  1.60465116 -0.03654485]

Solution using Gaussian Elimination (NumpPy):
[-0.16943522  1.60465116 -0.03654485]

Verification (Ax = b):
[16. 18. 14.]
